-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-05-07 20:59:32 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

-- procedure "ZRUS_ALL_OBJEKTY_SCHEMATU" pouzita ze vzorove prace
set echo on
CREATE OR REPLACE PROCEDURE "ZRUS_ALL_OBJEKTY_SCHEMATU" AS
-- pokud v logu bude uvedeno, ze nektery objekt nebyl zrusen, protoze na nej jiny jeste existujici objekt stavi,
-- spust proceduru opakovane, dokud se nezrusi vse
v_pom PLS_INTEGER;
BEGIN
LOOP
FOR irec IN (SELECT DISTINCT
                    object_type,object_name,
                    'drop '||object_type||' "'||object_name||'"'||
                    CASE object_type WHEN 'TABLE' THEN ' cascade constraints purge'
                                     ELSE ' '
                    END AS prikaz
              FROM user_objects
              WHERE object_name <> 'ZRUS_ALL_OBJEKTY_SCHEMATU'
            )
  LOOP
   BEGIN
   DBMS_OUTPUT.put_line('prikaz '||irec.prikaz);
      EXECUTE IMMEDIATE irec.prikaz;
   EXCEPTION
      WHEN OTHERS THEN DBMS_OUTPUT.put('není ');
   END;
   DBMS_OUTPUT.put_line('zrusen(a) '||irec.object_type||' '||irec.object_name);
  END LOOP;
SELECT COUNT(*) INTO v_pom
FROM user_objects
WHERE object_name <> 'ZRUS_ALL_OBJEKTY_SCHEMATU';
EXIT WHEN v_pom = 0;
END LOOP;
DBMS_OUTPUT.put_line('hotovo!');
END ZRUS_ALL_OBJEKTY_SCHEMATU;
/
execute ZRUS_ALL_OBJEKTY_SCHEMATU

CREATE TABLE Budova
  (
    Budova_Key NUMBER (10) NOT NULL ,
    Adr_Mesto  VARCHAR2 (20 CHAR) NOT NULL ,
    Adr_Ulice  VARCHAR2 (20 CHAR) NOT NULL ,
    Adr_Cislo  VARCHAR2 (10 CHAR) NOT NULL
  ) ;
ALTER TABLE Budova ADD CONSTRAINT Budova_PK PRIMARY KEY ( Budova_Key ) ;


CREATE TABLE Katedra
  (
    Katedra_Key   NUMBER (5) NOT NULL ,
    Nazev_Katedra VARCHAR2 (50 CHAR) NOT NULL
  ) ;
ALTER TABLE Katedra ADD CHECK ( Katedra_Key BETWEEN 10000 AND 19999) ;
ALTER TABLE Katedra ADD CONSTRAINT Katedra_PK PRIMARY KEY ( Katedra_Key ) ;


CREATE TABLE Kolej
  (
    Nazev_Kolej VARCHAR2 (20 CHAR) NOT NULL ,
    Adr_Mesto   VARCHAR2 (20 CHAR) NOT NULL ,
    Adr_Ulice   VARCHAR2 (20 CHAR) NOT NULL ,
    Adr_Cislo   VARCHAR2 (10 CHAR) NOT NULL
  ) ;
ALTER TABLE Kolej ADD CONSTRAINT Kolej_PK PRIMARY KEY ( Nazev_Kolej ) ;


CREATE TABLE Predmet
  (
    Kod_Predmet   VARCHAR2 (10 CHAR) NOT NULL ,
    Nazev_Predmet VARCHAR2 (50 CHAR) NOT NULL ,
    Zakonceni     VARCHAR2 (2 CHAR) NOT NULL ,
    Kredity       NUMBER (1) NOT NULL ,
    Katedra_Key   NUMBER (5) NOT NULL
  ) ;
ALTER TABLE Predmet ADD CHECK ( Zakonceni IN ('KZ', 'Z', 'ZK')) ;
ALTER TABLE Predmet ADD CONSTRAINT Predmet_PK PRIMARY KEY ( Kod_Predmet ) ;


CREATE TABLE Sport
  (
    Nazev_Sport VARCHAR2 (30 CHAR) NOT NULL ,
    Popis       VARCHAR2 (100 CHAR)
  ) ;
ALTER TABLE Sport ADD CONSTRAINT Sport_PK PRIMARY KEY ( Nazev_Sport ) ;


CREATE TABLE Student
  (
    Student_Key    NUMBER (6) NOT NULL ,
    Jmeno          VARCHAR2 (30 CHAR) NOT NULL ,
    Prijmeni       VARCHAR2 (30 CHAR) NOT NULL ,
    Datum_narozeni DATE NOT NULL ,
    Tel_Cislo      NUMBER NOT NULL ,
    Email          VARCHAR2 (30 CHAR) NOT NULL ,
    Titul          VARCHAR2 (30 CHAR) ,
    Rok_Nastupu    NUMBER (4) NOT NULL ,
    Nazev_Kolej    VARCHAR2 (20 CHAR)
  ) ;
ALTER TABLE Student ADD CONSTRAINT Student_PK PRIMARY KEY ( Student_Key ) ;


CREATE TABLE Ucebna
  (
    Mistnost      NUMBER (4) NOT NULL ,
    Patro         NUMBER (2) NOT NULL ,
    Budova_Key    NUMBER (10) NOT NULL ,
    Pocet_Sedadel NUMBER (3) NOT NULL
  ) ;
ALTER TABLE Ucebna ADD CONSTRAINT Ucebna_PK PRIMARY KEY ( Mistnost, Budova_Key ) ;


CREATE TABLE Vysledek
  (
    Zapis_Key NUMBER (7) NOT NULL ,
    Znamka    VARCHAR2 (1 CHAR) NOT NULL ,
    Body      NUMBER (3)
  ) ;
ALTER TABLE Vysledek ADD CHECK ( Znamka IN ('A', 'B', 'C', 'D', 'E', 'F')) ;
ALTER TABLE Vysledek ADD CHECK ( Body BETWEEN 0 AND 150) ;
ALTER TABLE Vysledek ADD CONSTRAINT Vysledek_PK PRIMARY KEY ( Zapis_Key ) ;


CREATE TABLE Zamestnanec
  (
    Zamestnanec_Key   NUMBER (6) NOT NULL ,
    Jmeno             VARCHAR2 (30 CHAR) NOT NULL ,
    Prijmeni          VARCHAR2 (30 CHAR) NOT NULL ,
    Datum_narozeni    DATE NOT NULL ,
    Tel_Cislo         NUMBER NOT NULL ,
    Email             VARCHAR2 (30 CHAR) NOT NULL ,
    Titul             VARCHAR2 (30 CHAR) ,
    Smlouva_Od        DATE NOT NULL ,
    Pracovni_zarazeni VARCHAR2 (20 CHAR) NOT NULL ,
    Plat              NUMBER (6) ,
    Katedra_Key       NUMBER (5)
  ) ;
ALTER TABLE Zamestnanec ADD CONSTRAINT Zamestnanec_PK PRIMARY KEY ( Zamestnanec_Key ) ;


CREATE TABLE Zapis
  (
    Zapis_Key       NUMBER (7) NOT NULL ,
    S_Rok           NUMBER (4) NOT NULL ,
    Semestr         VARCHAR2 (5 CHAR) NOT NULL ,
    Kod_Predmet     VARCHAR2 (10 CHAR) NOT NULL ,
    Student_Key     NUMBER (6) NOT NULL ,
    Mistnost        NUMBER (4) NOT NULL ,
    Budova_Key      NUMBER (10) NOT NULL ,
    Zamestnanec_Key NUMBER (6) NOT NULL
  ) ;
ALTER TABLE Zapis ADD CHECK ( Semestr IN ('Letni', 'Zimni')) ;
ALTER TABLE Zapis ADD CONSTRAINT Zapis_PK PRIMARY KEY ( Zapis_Key ) ;


CREATE TABLE Zapis_Sport
  (
    Zapis_Sport_Key NUMBER (5) NOT NULL ,
    S_Rok           NUMBER (4) NOT NULL ,
    Semestr         VARCHAR2 (5 CHAR) NOT NULL ,
    Nazev_Sport     VARCHAR2 (30 CHAR) NOT NULL ,
    Student_Key     NUMBER (6) NOT NULL
  ) ;
ALTER TABLE Zapis_Sport ADD CHECK ( Semestr IN ('Letni', 'Zimni')) ;
ALTER TABLE Zapis_Sport ADD CONSTRAINT Zapis_Sport_PK PRIMARY KEY ( Zapis_Sport_Key ) ;


CREATE TABLE Zaverecna_prace
  (
    Prace_Key       NUMBER (4) NOT NULL ,
    Tema            VARCHAR2 (50) NOT NULL ,
    Popis           VARCHAR2 (100) ,
    Student_Key     NUMBER (6) NOT NULL ,
    Zamestnanec_Key NUMBER (6) NOT NULL
  ) ;
ALTER TABLE Zaverecna_prace ADD CONSTRAINT Zaverecna_prace_PK PRIMARY KEY ( Prace_Key ) ;


ALTER TABLE Predmet ADD CONSTRAINT Predmet_Katedra_FK FOREIGN KEY ( Katedra_Key ) REFERENCES Katedra ( Katedra_Key ) ;

ALTER TABLE Student ADD CONSTRAINT Student_Kolej_FK FOREIGN KEY ( Nazev_Kolej ) REFERENCES Kolej ( Nazev_Kolej ) ;

ALTER TABLE Ucebna ADD CONSTRAINT Ucebna_Budova_FK FOREIGN KEY ( Budova_Key ) REFERENCES Budova ( Budova_Key ) ;

ALTER TABLE Vysledek ADD CONSTRAINT Vysledek_Zapis_FK FOREIGN KEY ( Zapis_Key ) REFERENCES Zapis ( Zapis_Key ) ;

ALTER TABLE Zamestnanec ADD CONSTRAINT Zamestnanec_Katedra_FK FOREIGN KEY ( Katedra_Key ) REFERENCES Katedra ( Katedra_Key ) ;

ALTER TABLE Zapis ADD CONSTRAINT Zapis_Predmet_FK FOREIGN KEY ( Kod_Predmet ) REFERENCES Predmet ( Kod_Predmet ) ;

ALTER TABLE Zapis_Sport ADD CONSTRAINT Zapis_Sport_Sport_FK FOREIGN KEY ( Nazev_Sport ) REFERENCES Sport ( Nazev_Sport ) ;

ALTER TABLE Zapis_Sport ADD CONSTRAINT Zapis_Sport_Student_FK FOREIGN KEY ( Student_Key ) REFERENCES Student ( Student_Key ) ;

ALTER TABLE Zapis ADD CONSTRAINT Zapis_Student_FK FOREIGN KEY ( Student_Key ) REFERENCES Student ( Student_Key ) ;

ALTER TABLE Zapis ADD CONSTRAINT Zapis_Ucebna_FK FOREIGN KEY ( Mistnost, Budova_Key ) REFERENCES Ucebna ( Mistnost, Budova_Key ) ;

ALTER TABLE Zapis ADD CONSTRAINT Zapis_Zamestnanec_FK FOREIGN KEY ( Zamestnanec_Key ) REFERENCES Zamestnanec ( Zamestnanec_Key ) ;

ALTER TABLE Zaverecna_prace ADD CONSTRAINT Zaverecna_prace_Student_FK FOREIGN KEY ( Student_Key ) REFERENCES Student ( Student_Key ) ;

ALTER TABLE Zaverecna_prace ADD CONSTRAINT Zaverecna_prace_Zamestnanec_FK FOREIGN KEY ( Zamestnanec_Key ) REFERENCES Zamestnanec ( Zamestnanec_Key ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
